### PR TITLE
MEN-3152: add support for fallback RSA private key

### PR DESCRIPTION
**Pull request by tranchitella**
New configuration setting (server_fallback_priv_key_path) and env
variable (DEVICEAUTH_SERVER_FALLBACK_PRIV_KEY_PATH) to specify a
fallback RSA private key to be used to verify signatures on JWT token.

Specifying a fallback RSA private key it is possible to rotate the
private key used by the service.

Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by kjaskiewiczz — APPROVED** [review]
looks good

**Comment by tranchitella** [comment]
File transfer failures are unrelated to this PR.

**Pull request merged**
