### PR TITLE
Changelog:All: Bump alpine from 3.14.2 to 3.15.0

### PR DESCRIPTION
**Pull request by merlin-northern**
Bumps alpine from 3.14.2 to 3.15.0.

---
updated-dependencies:
- dependency-name: alpine
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
(cherry picked from commit e89cba34a42277836ce051094c8121c519ad5275)
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
for some reason this one:https://github.com/mendersoftware/deviceauth/pull/556 failed tests, probably needed rebase.

**Comment by mzedel** [comment]
> for some reason this one:#556 failed tests, probably needed rebase.

FYI: you can always request such things straight from dependabot via `@dependabot rebase` 🪄

**Review by mzedel — APPROVED** [review]

**Comment by merlin-northern** [comment]
> > for some reason this one:#556 failed tests, probably needed rebase.
> 
> FYI: you can always request such things straight from dependabot via `@dependabot rebase` 🪄

I know, but I was on fire elsewhere. thanks.

**Pull request merged**
