### PR TITLE
MEN-3972: ignore tenant claim in single tenant setup

### PR DESCRIPTION
**Pull request by kjaskiewiczz**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
properly configured pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/229952372

**Comment by kjaskiewiczz** [comment]
it's a backport of https://github.com/mendersoftware/deviceauth/pull/427 to 2.4.x

**Comment by kjaskiewiczz** [comment]
and one more pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/230010190

**Review by alfrunes — APPROVED** [review]

**Comment by kjaskiewiczz** [comment]
successful pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/230717806

**Pull request merged**
