### PR TITLE
vendor: Migrate to `go mod` for tracking vendored dependencies

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by mzedel** [comment]
shall I merge https://github.com/mendersoftware/deviceauth/pull/315 and then you merge this one? or would you just get the dependabot config in here? + there also is #317

**Comment by alfrunes** [comment]
> One question: I think the gitlab file needs a bump in the go version as well (`tests:static` and `tests:unit` jobs).
> I was moving to 1.13, which is the default on gitlab so I just removed the `image` tags, but imo 1.14 needs to be explicitly stated.

Good point, I'll bump the golang version to 1.14.

**Comment by alfrunes** [comment]
> shall I merge #315 and then you merge this one? or would you just get the dependabot config in here? + there also is #317

That's up to you, I suppose I could just cherry pick that config file here if you want?
I didn't notice #317, but if @merlin-northern approves maybe we could continue with the migration here?

**Comment by merlin-northern** [comment]
> > shall I merge #315 and then you merge this one? or would you just get the dependabot config in here? + there also is #317
> 
> That's up to you, I suppose I could just cherry pick that config file here if you want?
> I didn't notice #317, but if @merlin-northern approves maybe we could continue with the migration here?

no problem -- what ever is more comfortable! it is fine by me whatever you decide.

**Comment by mzedel** [comment]
> > shall I merge #315 and then you merge this one? or would you just get the dependabot config in here? + there also is #317
> 
> That's up to you, I suppose I could just cherry pick that config file here if you want?
> I didn't notice #317, but if @merlin-northern approves maybe we could continue with the migration here?

yes, please cherry-pick the config and merge it all in one swoop 🎉

**Pull request merged**
