### PR TITLE
MEN-3763 GetDevicesById

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@merlin-northern What's the status of this PR?

**Comment by mzedel** [comment]
@tranchitella & @merlin-northern this would be very relevant for the reported issues about multi-authset devices no longer refreshing in the gui...

**Comment by merlin-northern** [comment]
> @merlin-northern What's the status of this PR?

this one was made in a spare moment, but unfinished, so thats why it is a draft. at the time it was created it was not critical -- I see now it gained importance. I will revisit.

**Comment by merlin-northern** [comment]
> @tranchitella & @merlin-northern this would be very relevant for the reported issues about multi-authset devices no longer refreshing in the gui...

I think thats why I started with it. maybe during the weekend I will get a chance to take a look at it.

**Comment by merlin-northern** [comment]
> @merlin-northern What's the status of this PR?

the feature is ready -- it lack tests, I am working on it when time permits.

**Comment by alfrunes** [comment]
@merlin-northern psst! You can open this draft PR now ;)

**Comment by merlin-northern** [comment]
> @merlin-northern psst! You can open this draft PR now ;)

right!

**Comment by alfrunes** [comment]
Superseded by #426

**Pull request closed without merging**
