### PR TITLE
MEN-4208: add tenant_id input parameter to the decommissioning workflow

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
Manual pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/230507210
Depends on:
* https://github.com/mendersoftware/workflows/pull/100
* https://github.com/mendersoftware/workflows-enterprise/pull/142

**Comment by tranchitella** [comment]
PIpeline is green, but not reported because I skipped the Client acceptance tests to limit costs.

**Review by alfrunes — COMMENTED** [review]
I'm pretty sure I added both `tenant_id` and `device_id` to this workflow in #419. What happened?

**Comment by tranchitella** [comment]
@alfrunes you did it for the provisioning, not for the decommissioning. Can it be?

**Comment by alfrunes** [comment]
Ohh, right! My bad.

**Review by alfrunes — APPROVED** [review]

**Pull request merged**
