### PR TITLE
Feature/dependabot

### PR DESCRIPTION
**Pull request by mzedel**

### CODE REVIEW

**Comment by oleorhagen** [comment]
The vendor folder has to be updated also:
```bash
go mod vendor
```

**Comment by mzedel** [comment]
@oleorhagen wouldn't this switch to go modules entirely? if that's ok, I'll happily make the step - otherwise I'll leave that to another time...

**Comment by oleorhagen** [comment]
> @oleorhagen wouldn't this switch to go modules entirely? if that's ok, I'll happily make the step - otherwise I'll leave that to another time...

It would. Fine with me. But I guess @tranchitella should have the final word here?

**Comment by mzedel** [comment]
closing for #350

**Pull request closed without merging**
