### PR TITLE
chore: logging fixes: jti.String() with %s

### PR DESCRIPTION
**Pull request by merlin-northern**
Ticket: None

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Comment by merlin-northern** [comment]
the pipeline passed, the latter push was only fmt.

**Review by alfrunes — COMMENTED** [review]
I'm not sure what this PR is addressing. According to the [docs](https://pkg.go.dev/fmt), for types that implement the `fmt.Stringer` interface, this value should be called on the `%s` verb.

**Review by alfrunes — COMMENTED** [review]
I'm not sure what this PR is addressing. According to the [docs](https://pkg.go.dev/fmt), for types that implement the `fmt.Stringer` interface, this value should be called on the `%s` verb.

**Comment by merlin-northern** [comment]
> I'm not sure what this PR is addressing. According to the [docs](https://pkg.go.dev/fmt), for types that implement the `fmt.Stringer` interface, this value should be called on the `%s` verb.

this PR is addressing the really misleading logs which make live debugging sessions and trouble shooting even more difficult:

```
time="2023-05-25T22:13:21Z" level=error msg="Token  invalid: jwt: token expired" device_id=xxx file=devauth.go func="devauth.(*DevAuth).VerifyToken" line=1273 plan=enterprise request_id=xxx tenant_id=xxx
time="2023-05-25T22:13:20Z" level=error msg="jwt: token invalid" device_id=xxx file=api_devauth.go func="http.(*DevAuthApiHandlers).VerifyTokenHandler" line=490 plan=enterprise request_id=xxx tenant_id=xxx
time="2023-05-25T22:13:20Z" level=error msg="Token  invalid: jwt: token expired" device_id=xxx file=devauth.go func="devauth.(*DevAuth).VerifyToken" line=1273 plan=enterprise request_id=xxx tenant_id=xxx
```

this is from the field.

**Review by alfrunes — APPROVED** [review]

**Pull request merged**
