### PR TITLE
fix: propagate id data to inventory for all tenants case.

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: Title
Ticket: None

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Comment by merlin-northern** [comment]
> LGTM We also need to fix the command for reporting as well, but we can create a ticket for that since it's not so urgent.

I checked the reporting as well, should be ok, or did you see something there?

**Comment by alfrunes** [comment]
> I checked the reporting as well, should be ok, or did you see something there?

I thought I saw something, but when I looked again it all looks ok. Maybe I'm just seeing things? :ghost:

**Comment by merlin-northern** [comment]
> > I checked the reporting as well, should be ok, or did you see something there?
> 
> I thought I saw something, but when I looked again it all looks ok. Maybe I'm just seeing things? 👻

haha :) as long as they are nice things that you want to see again you are ok :) thanks for being vigilant!

**Pull request merged**
