### PR TITLE
MEN-4512: Addon restrictions for devices

### PR DESCRIPTION
**Pull request by alfrunes**
Since there are no plan restrictions for devices (yet) I didn't implement that part, but I tried to keep the `access` package flexible with this in mind.

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by mchalski — APPROVED** [review]
looks good.

FTR I had some doubts about maybe also introducing `TestToken` open source - but it doesn't make sense. `deviceconfig` will not even be there in the open source setup...

(it did make sense to test both setups in useradm-enterprise - but only because they effectively translate to 'enterprise hosted' and 'enterprise onprem', so it was a good opportunity to check that addons are bypassed if !HAVE_ADDONS, which will be 99% of cases for onprem users, they're not interested in this at all. this is not the case here, but anywa, I'm rambling, approved :) )

**Comment by alfrunes** [comment]
The integration test errors appears to be spurious. I tested the failing tests locally and obtained the following results:
 * `test_bogus_protomsg`: passed
 * `test_filetransfer`: passed
 * `test_configuration`: passed for open source test and failed for enterprise (the opposite of what happened in the pipeline).

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Pull request merged**
