### PR TITLE
MEN-3972: ignore tenant claim in single tenant setup

### PR DESCRIPTION
**Pull request by kjaskiewiczz**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
properly configured pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/229966397

**Comment by kjaskiewiczz** [comment]
it's a backport of https://github.com/mendersoftware/deviceauth/pull/427 to 2.3.x

**Comment by lluiscampos** [comment]
New build @ [Pipeline 229986404](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/229986404) started with:

```
release_tool -b 2.4.x --pr mender/2.3.1 --pr meta-mender/dunfell --pr deviceauth/441
```

**Review by alfrunes — APPROVED** [review]
LGTM

**Pull request merged**
