### PR TITLE
refactor: do not store the public key in the device document

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr deviceauth-enterprise/48

**Review by mzedel — CHANGES_REQUESTED** [review]
I'm sorry to bring bad news, but the [gui code](https://github.com/mendersoftware/gui/blob/master/src/js/components/devices/device-details/authsets/authsetlistitem.js#L90-L105) uses the key... if you can provide a separate endpoint (+ maybe bump the api version of this one) we could likely still get the optimization benefits

**Review by MaciejTe — APPROVED** [review]
It looks good from my perspective. Pre approving (please make sure these changes do not collide with GUI, as Manuel mentioned). Thanks!

**Comment by tranchitella** [comment]
> I'm sorry to bring bad news, but the [gui code](https://github.com/mendersoftware/gui/blob/master/src/js/components/devices/device-details/authsets/authsetlistitem.js#L90-L105) uses the key... if you can provide a separate endpoint (+ maybe bump the api version of this one) we could likely still get the optimization benefits

I think you are wrong: you are processing the pubkey field of the authset. Here I'm talking about the pubkey field of the device, which is not even returned from the API.

image

**Review by mzedel — APPROVED** [review]
Excellent, thanks for the clarification and sorry for not checking this in depth!

**Review by alfrunes — APPROVED** [review]

**Pull request merged**
