### PR TITLE
jwt: Include 'mender.addons' claim for listing tenant addons

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by mchalski** [comment]
@alfrunes I wanted to take a look, but I can't dig out the real change, files changed is ~400 in the first commit.
is the vendor update by design here, or a glitch?

**Comment by alfrunes** [comment]
@mchalski The actual change is the first files in the diff before the `vendor/*` section begins (minus the `LIC_FILES_CHCKSUMS.sha256`). I had to update the vendored version of `go-lib-micro` to get the addons definitions, which unfortunately pulled in a lot of indirect dependencies.

**Comment by mchalski** [comment]
@alfrunes gotcha, could you `rebase -i + edit` out the real changes into an extra commit?
the file view errors out for me... from what I see the changes look ok, but I'd like to be sure.

**Comment by alfrunes** [comment]
> @alfrunes gotcha, could you `rebase -i + edit` out the real changes into an extra commit?
> the file view errors out for me... from what I see the changes look ok, but I'd like to be sure.

@mchalski done!

**Review by mchalski — APPROVED** [review]
alrighty, looks good!

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline (sorry, I forgot)

**Pull request merged**
