### PR TITLE
move doc file from internal_api.yml -> management_api.yml

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@bboozzoo

**Comment by GregorioDiStefano** [comment]
@maciejmrowiec can you force merge this? tests wont pass due to old client that we cant update at the moment

**Comment by maciejmrowiec** [comment]
Wait, Wait those are internal API's, why do we publish them?

**Comment by GregorioDiStefano** [comment]
wrong file being renamed

**Pull request closed without merging**
