### PR TITLE
MC-7155: Update accesslog middleware and fix auth request Content-Type

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by kjaskiewiczz — APPROVED** [review]

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Pull request merged**
