### PR TITLE
api_devauth: remove endpoints with no implementation

### PR DESCRIPTION
**Pull request by bboozzoo**
Removing endpoints that have no implementation and are not covered by the spec.

Fixes: [MEN #969]

@maciejmrowiec @mendersoftware/rndity

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
What about cleaning up swagger ?

**Comment by bboozzoo** [comment]
These were not listed in swagger spec at all.

**Comment by maciejmrowiec** [comment]
where does this come from then: https://docs.mender.io/APIs/Integration-APIs/Device-authentication#devices-get :/

**Comment by bboozzoo** [comment]
Beats me. Talk to @GregorioDiStefano from what I've been told, the docs size it outdated

**Comment by maciejmrowiec** [comment]
alright then

**Comment by maciejmrowiec** [comment]
merging as build is failing because of key change

**Pull request merged**
