### PR TITLE
Single db move fixes

### PR DESCRIPTION
**Pull request by merlin-northern**

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@alfrunes please review only last commit: https://github.com/mendersoftware/deviceauth/pull/642/commits/b8f8dc2c8f2dd31137340f3b5cdaa2c057db856f the rest is the feature branch: signle_db_move to which I will re-target the PR as soon as all the pipelines are green.

**Review by alfrunes — APPROVED** [review]

**Comment by alfrunes** [comment]
Can you also remove the .golangci-lint file?

**Comment by merlin-northern** [comment]
> Can you also remove the .golangci-lint file?

sure thank you. and sorry, this was a leftover from the scirpt.

**Comment by merlin-northern** [comment]
> > Can you also remove the .golangci-lint file?
> 
> sure thank you. and sorry, this was a leftover from the scirpt.

[removed](https://github.com/mendersoftware/deviceauth/pull/642/commits/a905adec040f6be3de8355c2621c86d39c32c104)

**Pull request merged**
